name: Ship

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  ship:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Node
      uses: actions/setup-node@v2.4.1
      with:
        cache: 'npm'
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Deploy CDK app
      run: npm run cdk deploy -- --require-approval never
